{{- if ne .Values.global.proxySecretFile "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.proxySecretName }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    kubescape.io/ignore: "true"
type: Opaque
data:
  proxy.crt: {{ .Values.global.proxySecretFile | quote }}
{{- end }}
