{{- $components := fromYaml (include "components" .) }}
  {{- if $components.operator.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    kubescape.io/ignore: "true"
data:
  config.json: |
    {
        "namespace": "{{ .Values.ksNamespace }}",
        "triggersecurityframework": {{ .Values.operator.triggerSecurityFramework }}
    }
{{- end }}
