kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.continuousScanning.configMapName }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    app: {{ .Values.ksLabel }}
    tier: {{ .Values.global.namespaceTier }}
    kubescape.io/ignore: "true"
data:
  matchingRules.json: |
    {{ mustToJson .Values.continuousScanning.matchingRules }}
